### ISSUE TITLE
Wrong locale in backend translation

### ISSUE THREAD

**Issue by momolog** [owen2345/camaleon-cms#233]
using camaleon_cms version:
```
  remote: git://github.com/owen2345/camaleon-cms.git
  revision: a6d499b81ac9729fb055d3782d50ef5c19f58900
  branch: moduler
```
I chose 'de' as first *frontend* language and 'en' as backend language.

![admin panel settings languages](https://cloud.githubusercontent.com/assets/71108/11443487/dce5d370-951d-11e5-9a2a-df0e0f8deda4.jpg)

Now some strings in the backend are tried to be translated to *german* instead of english, e.g. in the login form:

![span class _translation_missing_ title _translation missing_ de camaleon_cms admin login login_ login _span](https://cloud.githubusercontent.com/assets/71108/11443520/1551aa68-951e-11e5-8028-97e3158e4f57.jpg)

or here:

![admin panel settings languages-1](https://cloud.githubusercontent.com/assets/71108/11443506/f53a88f8-951d-11e5-80e6-7449b41bb434.jpg)

**Comment by owen2345** [comment]
thank you for the report, I will review right now!

**Comment by owen2345** [comment]
Hey @momolog 
I tried to reproduce the error, but without success:
![screen shot 2015-11-28 at 5 37 57 am](https://cloud.githubusercontent.com/assets/1148415/11451168/4841536e-9592-11e5-8fdd-a7a5961a97af.png)
![screen shot 2015-11-28 at 5 37 24 am](https://cloud.githubusercontent.com/assets/1148415/11451167/4840dea2-9592-11e5-8b46-2adbb6d5a558.png)

**Comment by momolog** [comment]
@owen2345 I can make the app repo + db available to you, if this helps.

**Comment by owen2345** [comment]
please do it!

**Comment by asn** [comment]
Anything new to this issue?

**Comment by owen2345** [comment]
Hi @asn 
this problem should be already fixed in branch master.
Regards,

**Comment by asn** [comment]
Hi @owen2345,

when i choose German as a primary and only language for the frontend. I get a 
undefined method `cama_category_en_url' Error. Do you have any hints to fix this?
Greetings 
Axel


 #<#<Class:0x007ffaac40f9a8>:0x007ffaac6608d8>
Extracted source (around line #38):
36
37
38
39
40
              
    end
    options.delete(:format) if PluginRoutes.system_info["skip_format_url"].present?
    send(url_to, *(args << options))
  end
end

Rails.root: /Users/asn/workspace/baza.space/blog

Application Trace | Framework Trace | Full Trace
camaleon_cms (2.1.1.4) app/helpers/camaleon_cms/frontend/application_helper.rb:38:in `cama_url_to_fixed'
draper (1.4.0) lib/draper/helper_proxy.rb:29:in `block in define_proxy'
camaleon_cms (2.1.1.4) app/decorators/camaleon_cms/category_decorator.rb:21:in `the_url'
camaleon_cms (2.1.1.4) app/views/camaleon_cms/admin/categories/index.html.erb:44:in `_item_html'
camaleon_cms (2.1.1.4) app/views/camaleon_cms/admin/categories/index.html.erb:51:in `block in _render_categories'
activerecord (4.2.5) lib/active_record/relation/delegation.rb:46:in `each'
activerecord (4.2.5) lib/active_record/relation/delegation.rb:46:in `each'
camaleon_cms (2.1.1.4) app/views/camaleon_cms/admin/categories/index.html.erb:50:in `_render_categories'
camaleon_cms (2.1.1.4) app/views/camaleon_cms/admin/categories/index.html.erb:56:in `___sers_asn__rvm_gems_ruby_______bazablog_gems_camaleon_cms_________app_views_camaleon_cms_admin_categories_index_html_erb___1915754062651925566_70357305307120'
actionview (4.2.5) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.5) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.5) lib/action_view/template.rb:143:in `render'
actionview (4.2.5) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.5) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'

**Comment by asn** [comment]
The Problem still exists. 

Master or stable branch are not fixing the problem.

<img width="601" alt="bildschirmfoto 2016-04-28 um 12 45 47" src="https://cloud.githubusercontent.com/assets/145752/14883582/3d196e2a-0d3f-11e6-8e95-d80447e9ef37.png">

Please reopen this issue

**Comment by owen2345** [comment]
@asn the problem with category url was fixed!
please try again!

**Comment by asn** [comment]
@owen2345 thx a lot - it seems to be running very well 
Great!
Thx again.
Axel
